import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Quote Generator",
  description: "Generated by create next app",
};


import './globals.css';
import { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-black">
       < header className="w-full bg-white shadow-md p-6 text-center text-3xl font-extrabold text-gray-800">Quote Generator</header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}


